# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: ocean
day_night: false
font: minimal
font_size: S

# SEO

site_type: Organization
local_business_type: ''
org_name: 'UC San Diego'
description: The Human-centered eXtended Intelligence Research Lab at UC San Diego focuses on the design, development, and evaluation of interactive technology across Ubiquitous Computing, Artificial Intelligence (AI), eXtended Reality (XR), and immersive visualization.
twitter: ''

# Contact (edit or remove options as required)

address: 
  street: 'Dr. Nadir Weibel, Ph.D.<br/>University of California, San Diego<br/>Computer Science and Engineering</br>Mail Code #0404<br/>9500 Gilman Drive<br/>La Jolla, CA 92093, USA'
  city: 
  region: 
  postcode:
  country: United States
  country_code: US
email: hxi@ucsd.edu
phone: 858-534-8637
coordinates: 
  latitude: '32.88190193654606'
  longitude: '-117.23349879000372'
#coordinates: 
#  latitude: '32.8783565'
#  longitude: '--117.233496'
directions: The HXI Research Lab is located at the <a href="https://cse.ucsd.edu/about/directions-and-parking">Computer Science and Engineering Building</a> (CSE), and within the <a href="https://designlab.ucsd.edu/">Design Lab</a> at the Design and Innovation Building (DIB) on the main UCSD Campus in La Jolla.
#office_hours:
#  - 'Monday 10:00 to 13:00'
#  - 'Wednesday 09:00 to 10:00'
#appointment_url: 'https://calendly.com'
contact_links:
  - icon: building
    icon_pack: fas
    name: Prof. Weibel's Office in CSE - CSE 3224
    link: 'https://map.concept3d.com/?id=1005#!m/164780'
  - icon: building
    icon_pack: fas
    name: Prof. Weibel's Office in DIB - DIB 360
    link: 'https://goo.gl/maps/FaX3JPoK6MqLBYWSA'
  - icon: users
    icon_pack: fas
    name: Ph.D. students Lab in CSE - CSE 2238
    link: 'https://map.concept3d.com/?id=1005#!m/164780'
  - icon: users
    icon_pack: fas
    name: HCI Collaboratory in DIB - DIB 340+337
    link: 'https://goo.gl/maps/FaX3JPoK6MqLBYWSA'
  - icon: users
    icon_pack: fas
    name: CSE Undergraduate Lab in CSE - CSE 2217
    link: 'https://map.concept3d.com/?id=1005#!m/164780'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: false
  show_search: true
  highlight_active_link: false

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: false
math: false
diagram: false
privacy_pack: false
show_related:
  post: true
  project: true
  publication: true
  talk: true
reading_time: true
section_pager: false
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
comments:
  provider: ''
  commentable:
    page: true
    post: true
    docs: true
    project: true
    publication: true
    talk: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: 'UA-208916150-1'
  google_tag_manager: 'G-04M585SDRK'
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: main
  local_backend: false
icon:
  pack:
    ai: true
authors:
  show_posts: false
  search_exclude: true
assets:
  css:
    - css/custom.css
